### ISSUE TITLE
Query regarding performance

### ISSUE THREAD

**Issue by CosmoLuminous** [bdpedigo/sparse_decomposition#1]
Hi Benjamin @bdpedigo,

I just wanted to ask if this implementation is complete? 
Also i wanted to ask you if this algorithm practically performs better than existing Sparse PCA Algorithms or not as claimed by the authors in the paper?

**Comment by bdpedigo** [comment]
![diff-boxenplot](https://user-images.githubusercontent.com/25714207/111643344-475d1b00-87d5-11eb-94b2-625dbde1077e.png)

Hi @CosmoLuminous for SparseComponentAnalysis, at some point i made this figure comparing the difference in proportion of variance explained and the number of nonzeros in my implementation vs the original R implementation provided by the authors, and found that they looked pretty centered at 0 in both cases. meaning, the implementations seem to perform comparably (it is hard to make them identical due to randomness in a few places). Also I think the `.transform()` method for `SCA` may not be what some people want as its not necessarily an orthogonal projection, but if you are just decomposing a single matrix (and not projecting out-of-sample points) then that shouldnt matter. 

I do remember having a bug in the SparseMatrixApproximation code (the two-way decomposition), it ended up being less important for my work so i have yet to trace that down. Therefore I wouldn't recommend using that yet, happy to talk more if you need that one. 

Hope that helps... let me know if you have any questions.

**Comment by bdpedigo** [comment]
In practice, I found that it was much faster than the sparse PCA in sklearn, and did better on my problem. I make no claims about other sparse PCAs or applications since I didn't compare them, but the method was definitely useful for me.

**Comment by CosmoLuminous** [comment]
Thanks a lot for the details. 
Yes It would be great if you could provide me with the code for sparse matrix approximation. I may not need it immediately, but I might need it for the comparative analysis at later stages.

**Comment by bdpedigo** [comment]
> Thanks a lot for the details.

Sure!

> Yes It would be great if you could provide me with the code for sparse matrix approximation. I may not need it immediately, but I might need it for the comparative analysis at later stages.

I don't think I'll be able to work on this for a while, so i can't make any promises on this. if you need it urgently you can always use the original R implementation or even call that from python using rpy2

**Comment by CosmoLuminous** [comment]
Okay. Thank you.
